### ISSUE TITLE
RuntimeError: CUDA error: invalid device function 

### ISSUE THREAD

**Issue by henanjun** [matteo-ronchetti/torch-radon#11]
![image](https://user-images.githubusercontent.com/27271981/97309914-94c80280-189d-11eb-9fae-2f09cb7ae7ba.png)

**Comment by matteo-ronchetti** [comment]
What is your CUDA compute capability? You can obtain it by running
`python -c "import torch; print(torch.cuda.get_device_capability())"`

**Comment by henanjun** [comment]
> What is your CUDA compute capability? You can obtain it by running
> `python -c "import torch; print(torch.cuda.get_device_capability())"`
![image](https://user-images.githubusercontent.com/27271981/97313742-ee323080-18a1-11eb-9efd-35d0a50d62da.png)

**Comment by henanjun** [comment]
> What is your CUDA compute capability? You can obtain it by running
> `python -c "import torch; print(torch.cuda.get_device_capability())"`

like this..

**Comment by matteo-ronchetti** [comment]
OK, can you give me more detail about the error ? What is exactly the error and where are you encountering it?

**Comment by henanjun** [comment]
Ok, I installed torch-radon  and then ran "nosetests tests/ ".   It happens at "tests/test_torch.py" line 20: "z = torch.mean(radon.backprojection(y))"

**Comment by matteo-ronchetti** [comment]
The error is segmentation fault?

**Comment by henanjun** [comment]
Yes. like this..
![image](https://user-images.githubusercontent.com/27271981/97315810-0a36d180-18a4-11eb-9aaf-7d4558b2603b.png)

**Comment by matteo-ronchetti** [comment]
The main error is "invalid device function" which is caused by a CUDA function not being compiled for the device architecture of your GPU. This is surprising because your device compute capability is 7.0 and by default TorchRadon is compiled for that compute capability. Did you make any change to the setup.py? Can you try pulling the latest version from master and reinstalling the library?

**Comment by henanjun** [comment]
No, I dont make any changes of “setup.py”.  And I  pull the lastest version and reinstall  it.  The error still happens...

**Comment by matteo-ronchetti** [comment]
Can you edit line 20 of "tests/test_torch.py" and split it into 2 lines? Like this:
```python
z = radon.backprojection(y)
z = torch.mean(z)
```
I want to be sure that the problem is in `radon.backprojection` and not in `torch.mean`

**Comment by henanjun** [comment]
sry. i just left my office. I will do it tomorrow morning. ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Matteo&amp;nbsp;Ronchetti&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月27日(星期二) 晚上11:00
收件人:&nbsp;&quot;matteo-ronchetti/torch-radon&quot;<torch-radon@noreply.github.com&gt;;
抄送:&nbsp;&quot;Nanjun He&quot;<673640680@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [matteo-ronchetti/torch-radon] RuntimeError: CUDA error: invalid device function  (#11)

**Comment by henanjun** [comment]
> Can you edit line 20 of "tests/test_torch.py" and split it into 2 lines? Like this:
> 
> ```python
> z = radon.backprojection(y)
> z = torch.mean(z)
> ```
> 
> I want to be sure that the problem is in `radon.backprojection` and not in `torch.mean"

It seem likes the problem is in the 'torch.mean'.  The error is like this..

![image](https://user-images.githubusercontent.com/27271981/97385005-cc6d9380-190b-11eb-937f-53582d8a90f3.png)


**But I tried** 

> z =radon.backprojection(y)
>print(z)
 
**It can not print the value of z but notice a error like this..**

![image](https://user-images.githubusercontent.com/27271981/97384759-55d09600-190b-11eb-8347-9e59f780c201.png)

**Comment by henanjun** [comment]
Can you tell me  the version of  torch, cuda and python of your machine? Thank you..

**Comment by matteo-ronchetti** [comment]
I think you have a problem with your PyTorch installation. I have Python 3.7.7, PyTorch 1.6.0 and CUDA 10.2.

**Comment by henanjun** [comment]
I solved this problem by update the cuda 10.0 to 10.1.  Thanks for your kind reply.
